package com.ty.btm.entity;
// @Entity: Indicates that this class is a JPA entity and will be mapped to a database table.
// @Id: Specifies the primary key of the entity.
// @Getter, @Setter: Lombok annotations to automatically generate getter and setter methods for the class fields.
// @GeneratedValue(strategy = GenerationType.IDENTITY): Specifies that the primary key will be automatically generated by the database (auto-increment).
// @NoArgsConstructor, @AllArgsConstructor: Lombok annotations to generate constructors with no arguments and with all arguments respectively.
// @ToString: Lombok annotation to generate toString() method for debugging/logging purposes.
import java.time.LocalDateTime;
import java.util.List;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Entity // 
@Getter // 
@Setter 
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class User {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int userId;
	private String userName;
	private String userEmail;
	private String userPassword;
	private long userPhoneNumber;
	private LocalDateTime createdDateTime;
	private LocalDateTime updateDateTime;
	private Role role;
	@OneToMany
    private List<Task> tasks;

}
